version: '3.8'

services:

  app:
    build: .
    ports:
      - 8000:8000
    command: uvicorn controllers.main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379

  worker:
    build: .
    command: celery --app worker.celery:celery worker --concurrency=4 --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
      - app
      - db

  dashboard:
    image: mher/flower
    ports:
      - 5566:5566
    env_file:
      - .env
    depends_on:
      - redis
      - worker

volumes:
  postgres:
